# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown

# Site settings
baseurl: "/mangaleera" # the subpath of your site, e.g. /blog
url: "https://xhaleera.github.io" # the base hostname & protocol for your site

# Meta settings
title: Mangaleera » Chroniques manga
description: "Mangaleera : Chroniques manga, anime, Japon - Planning des sorties manga"
keywords: "manga, japon, anime, chronique, sortie, planning, librairie, bd"
google_verify: "_sh3dTOkxFbphrHcjok76nc3hyhie2kYfo5CAmyZBFg"

# Compress HTML
compress_html:
  blanklines: true

# Frontmatter defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/:slug"

# Collections
collections:
  - dossiers

# Useful
empty_array: []

exclude:
  - build_meta_pages.php
  - .vscode

include:
  - _archives
